[package]
name = "may"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
  ".",
  "crates/diagnostics",
  "crates/parser",
  "crates/semantics",
  "crates/verifier",
]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
diagnostics = { path = "crates/diagnostics" }
parser = { path = "crates/parser" }
semantics = { path = "crates/semantics" }
verifier = { path = "crates/verifier" }
